const images={
	blizzard: require('./images/blizzard.png'),
	breeze: require('./images/breeze.png'),
	cloudy_day: require('./images/cloudy-day.png'),
	cold: require('./images/cold.png'),
	dark_night: require('./images/dark-night.png'),
	drizzle: require('./images/drizzle.png'),
	drought: require('./images/drought.png'),
	flood: require('./images/flood.png'),
	foggy: require('./images/foggy.png'),
	hail_storm: require('./images/hail-storm.png'),
	hail: require('./images/hail.png'),
	hot_weather: require('./images/hot-weather.png'),
	hurricane: require('./images/hurricane.png'),
	lighting: require('./images/lighting.png'),
	mist: require('./images/mist.png'),
	moon_eclipse: require('./images/moon-eclipse.png'),
	night: require('./images/night.png'),
	overcast_day: require('./images/overcast-day.png'),
	partialy_cloudy: require('./images/partialy-cloudy.png'),
	pour_rain: require('./images/pour-rain.png'),
	puddles: require('./images/puddles.png'),
	rainbow: require('./images/rainbow.png'),
	rainy_day: require('./images/rainy-day.png'),
	sleet: require('./images/sleet.png'),
	smog: require('./images/smog.png'),
	snow_cloud: require('./images/snow-cloud.png'),
	sun_eclipse: require('./images/sun-eclipse.png'),
	sunny_day: require('./images/sunny-day.png'),
	temperature: require('./images/temperature.png'),
	windy_day: require('./images/windy-day.png'),
	menu_verticle_icon:require('./images/menu-vertical-icon-48.png'),
	check_yes:require('./images/chky.png'),
	check_no:require('./images/chkn.png')
}
export default images;